--------------------------------------------------------
--  File created - Wednesday-December-05-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NEWUSER
--------------------------------------------------------

  CREATE TABLE "HR"."NEWUSER" 
   (	"CUSTOMER_ID" NUMBER(10,0), 
	"CUSTOMER_CODE" VARCHAR2(10 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(30 BYTE), 
	"CUSTOMER_ADDRESS_1" VARCHAR2(100 BYTE), 
	"CUSTOMER_ADDRESS_2" VARCHAR2(100 BYTE), 
	"CUSTOMER_PIN_CODE" NUMBER(6,0), 
	"EMAIL_ADDRESS" VARCHAR2(100 BYTE), 
	"CONTACT_NUMBER" NUMBER(20,0), 
	"PRIMARY_CONTACT_PERSON" VARCHAR2(100 BYTE), 
	"RECORD_STATUS" VARCHAR2(1 BYTE), 
	"ACTIVEORINACTIVE_FLAG" VARCHAR2(1 BYTE), 
	"COLUMN1" DATE, 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(30 BYTE), 
	"AUTHORIZED_DATE" DATE, 
	"AUTHORIZED_BY" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
